const SET_LEVEL = 'SET_LEVEL'
const SET_INTERACTIVE_DATA = 'SET_INTERACTIVE_DATA'
const UPDATE_INTERACTIVE_DATA = 'UPDATE_INTERACTIVE_DATA'
const IS_CORRECT = 'IS_CORRECT'

export {
  SET_LEVEL,
  SET_INTERACTIVE_DATA,
  UPDATE_INTERACTIVE_DATA,
  IS_CORRECT,
}